version: '3'

services:
  # База данных
  db:
    image: postgres:13.0-alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ${HOME}/postgresql/data:/var/lib/postgresql/data 
    expose:
      - 5432
  # Приложение с django
  service:
    build: .
    expose:
      - 8000
    env_file:
      - ./app/config/.env
    depends_on:
      - db

  # Nginx
  nginx:
    image: nginx:1.21.6
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./app/static:/data/static:ro
    ports:
      - 80:80
    depends_on:
      - service
