# Generated by Django 4.1 on 2023-01-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="certificate",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="certificate"
            ),
        ),
        migrations.AddField(
            model_name="filmwork",
            name="file_path",
            field=models.FileField(
                blank=True, null=True, upload_to="movies/", verbose_name="file"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="birth_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="birth date"
            ),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[
                    ("actor", "actor"),
                    ("director", "director"),
                    ("writer", "writer"),
                ],
                default="actor",
                max_length=9,
            ),
        ),
    ]
